# Generated by Django 4.0 on 2022-01-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock_qty', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
