# Generated by Django 4.0 on 2022-01-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPSTORE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
