# Generated by Django 4.0 on 2022-01-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPSTORE', '0002_goods_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goods',
            name='stock_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goods',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
